export type Screen =
  | "dashboard"
  | "detail"
  | "nextSteps"
  | "actionChoice"
  | "archived"
  | "caseDetail"
  | "doItMyself"
  | "takeAction"
  | "payrollSummary"
  | "actionConfirmation"
  | "cashRedirects"
  | "redirectImpact"
  | "closingReview"
  | "caseClosed";